services:
  db:
    restart: "no"
    ports:
      - "127.0.0.1:5432:5432"

  prestart:
    environment:
      ENVIRONMENT: local

  backend:
    environment:
      ENVIRONMENT: local
    restart: "no"
    ports:
      - "127.0.0.1:8000:8000"
    build:
      context: .
      dockerfile: backend/Dockerfile
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app/backend
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
    volumes:
      - ./backend/htmlcov:/app/backend/htmlcov

  frontend:
    restart: "no"
    ports:
      - "127.0.0.1:5173:80"
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_URL: ""

  playwright:
    build:
      context: .
      dockerfile: frontend/Dockerfile.playwright
      args:
        NODE_ENV: production
    ipc: host
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - VITE_API_URL=
      - API_PROXY_TARGET=http://backend:8000
      - TEST_API_URL=http://backend:8000
      - PLAYWRIGHT_HTML_HOST=0.0.0.0
      - CI=${CI}
      - CLOUDATLAS_CAPSET_TOKEN=${CLOUDATLAS_CAPSET_TOKEN?Variable not set}
      - FIRST_SUPERUSER=${FIRST_SUPERUSER?Variable not set}
      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD?Variable not set}
    volumes:
      - ./frontend/blob-report:/app/frontend/blob-report
      - ./frontend/test-results:/app/frontend/test-results
    ports:
      - 127.0.0.1:9323:9323
