// This file is auto-generated by @hey-api/openapi-ts

export const AuditEventPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        tenant_id: {
            type: 'string',
            format: 'uuid',
            title: 'Tenant Id'
        },
        project_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Id'
        },
        actor_subject: {
            type: 'string',
            title: 'Actor Subject'
        },
        actor_type: {
            type: 'string',
            title: 'Actor Type'
        },
        action: {
            type: 'string',
            title: 'Action'
        },
        target_type: {
            type: 'string',
            title: 'Target Type'
        },
        target_id: {
            type: 'string',
            format: 'uuid',
            title: 'Target Id'
        },
        before_data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Before Data'
        },
        after_data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'After Data'
        },
        ip_address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ip Address'
        },
        occurred_at: {
            type: 'string',
            format: 'date-time',
            title: 'Occurred At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'tenant_id', 'project_id', 'actor_subject', 'actor_type', 'action', 'target_type', 'target_id', 'before_data', 'after_data', 'ip_address', 'occurred_at', 'created_at', 'updated_at'],
    title: 'AuditEventPublic'
} as const;

export const AuditEventsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AuditEventPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AuditEventsPublic'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CloudAtlasSourceCreateSchema = {
    properties: {
        instance_id: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Instance Id'
        },
        capset_id: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Capset Id'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['instance_id', 'capset_id'],
    title: 'CloudAtlasSourceCreate'
} as const;

export const CloudAtlasSourcePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        source_type: {
            type: 'string',
            title: 'Source Type'
        },
        instance_id: {
            type: 'string',
            title: 'Instance Id'
        },
        capset_id: {
            type: 'string',
            title: 'Capset Id'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        validation_status: {
            type: 'string',
            title: 'Validation Status'
        },
        fingerprint_summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fingerprint Summary'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'source_type', 'instance_id', 'capset_id', 'enabled', 'validation_status', 'fingerprint_summary', 'created_at', 'updated_at'],
    title: 'CloudAtlasSourcePublic'
} as const;

export const CloudAtlasSourceUpdateSchema = {
    properties: {
        instance_id: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Instance Id'
        },
        capset_id: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Capset Id'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['instance_id', 'capset_id'],
    title: 'CloudAtlasSourceUpdate'
} as const;

export const CloudAtlasSourceValidationRequestSchema = {
    properties: {
        capset_token: {
            type: 'string',
            maxLength: 4096,
            minLength: 1,
            format: 'password',
            title: 'Capset Token',
            writeOnly: true
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['capset_token'],
    title: 'CloudAtlasSourceValidationRequest'
} as const;

export const CloudAtlasSourcesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CloudAtlasSourcePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        can_manage: {
            type: 'boolean',
            title: 'Can Manage'
        }
    },
    type: 'object',
    required: ['data', 'count', 'can_manage'],
    title: 'CloudAtlasSourcesPublic'
} as const;

export const CustomerUploadProfilePublicSchema = {
    properties: {
        required_headers: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Required Headers'
        },
        warning_headers: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Warning Headers'
        },
        optional_headers: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Optional Headers'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        version: {
            type: 'integer',
            title: 'Version'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['required_headers', 'warning_headers', 'optional_headers', 'id', 'version'],
    title: 'CustomerUploadProfilePublic'
} as const;

export const CustomerUploadPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        display_filename: {
            type: 'string',
            title: 'Display Filename'
        },
        raw_sha256: {
            type: 'string',
            title: 'Raw Sha256'
        },
        record_count: {
            type: 'integer',
            title: 'Record Count'
        },
        profile_id: {
            type: 'string',
            format: 'uuid',
            title: 'Profile Id'
        },
        profile_version: {
            type: 'integer',
            title: 'Profile Version'
        },
        warnings: {
            items: {
                '$ref': '#/components/schemas/CustomerUploadWarningPublic'
            },
            type: 'array',
            title: 'Warnings'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'display_filename', 'raw_sha256', 'record_count', 'profile_id', 'profile_version', 'warnings', 'created_at'],
    title: 'CustomerUploadPublic'
} as const;

export const CustomerUploadWarningPublicSchema = {
    properties: {
        code: {
            type: 'string',
            title: 'Code'
        },
        field: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Field'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['code', 'field', 'count'],
    title: 'CustomerUploadWarningPublic'
} as const;

export const CustomerUploadsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CustomerUploadPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        current_customer_upload_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Customer Upload Id'
        },
        can_upload: {
            type: 'boolean',
            title: 'Can Upload'
        },
        can_select: {
            type: 'boolean',
            title: 'Can Select'
        }
    },
    type: 'object',
    required: ['data', 'count', 'current_customer_upload_id', 'can_upload', 'can_select'],
    title: 'CustomerUploadsPublic'
} as const;

export const GovernanceRunActionPublicSchema = {
    properties: {
        accepted: {
            type: 'boolean',
            title: 'Accepted'
        },
        action: {
            type: 'string',
            title: 'Action'
        },
        governance_run_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Governance Run Id'
        },
        source_governance_run_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Governance Run Id'
        },
        session_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Session Id'
        },
        agent_compose_run_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Agent Compose Run Id'
        },
        agent_compose_status: {
            type: 'string',
            title: 'Agent Compose Status'
        },
        code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Code'
        }
    },
    type: 'object',
    required: ['accepted', 'action', 'governance_run_id', 'session_id', 'agent_compose_run_id', 'agent_compose_status'],
    title: 'GovernanceRunActionPublic'
} as const;

export const GovernanceRunPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        trigger_id: {
            type: 'string',
            title: 'Trigger Id'
        },
        session_id: {
            type: 'string',
            title: 'Session Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        customer_upload_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Upload Id'
        },
        customer_upload_sha256: {
            type: 'string',
            title: 'Customer Upload Sha256'
        },
        customer_upload_profile_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Upload Profile Id'
        },
        customer_upload_profile_version: {
            type: 'integer',
            title: 'Customer Upload Profile Version'
        },
        source_instance_id: {
            type: 'string',
            format: 'uuid',
            title: 'Source Instance Id'
        },
        cloudatlas_validated_fingerprint: {
            type: 'string',
            title: 'Cloudatlas Validated Fingerprint'
        },
        cloudatlas_capset_id: {
            type: 'string',
            title: 'Cloudatlas Capset Id'
        },
        cloudatlas_method: {
            type: 'string',
            title: 'Cloudatlas Method'
        },
        package_sha256: {
            type: 'string',
            title: 'Package Sha256'
        },
        descriptor_sha256: {
            type: 'string',
            title: 'Descriptor Sha256'
        },
        runner_build_version: {
            type: 'string',
            title: 'Runner Build Version'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        },
        session_terminal_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Session Terminal At'
        },
        session_recovery_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Session Recovery Code'
        },
        steps: {
            items: {
                '$ref': '#/components/schemas/RunStepPublic'
            },
            type: 'array',
            title: 'Steps'
        },
        snapshots: {
            items: {
                '$ref': '#/components/schemas/SourceSnapshotPublic'
            },
            type: 'array',
            title: 'Snapshots'
        },
        reused_snapshot_count: {
            type: 'integer',
            title: 'Reused Snapshot Count',
            default: 0
        },
        can_retry: {
            type: 'boolean',
            title: 'Can Retry',
            default: false
        },
        can_rerun: {
            type: 'boolean',
            title: 'Can Rerun',
            default: false
        },
        blocking_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Blocking Code'
        }
    },
    type: 'object',
    required: ['id', 'trigger_id', 'session_id', 'status', 'customer_upload_id', 'customer_upload_sha256', 'customer_upload_profile_id', 'customer_upload_profile_version', 'source_instance_id', 'cloudatlas_validated_fingerprint', 'cloudatlas_capset_id', 'cloudatlas_method', 'package_sha256', 'descriptor_sha256', 'runner_build_version', 'created_at', 'completed_at', 'session_terminal_at', 'session_recovery_code', 'steps', 'snapshots'],
    title: 'GovernanceRunPublic'
} as const;

export const GovernanceRunTriggerPublicSchema = {
    properties: {
        accepted: {
            type: 'boolean',
            title: 'Accepted'
        },
        agent_compose_run_id: {
            type: 'string',
            title: 'Agent Compose Run Id'
        },
        agent_compose_status: {
            type: 'string',
            title: 'Agent Compose Status'
        },
        governance_run_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Governance Run Id'
        }
    },
    type: 'object',
    required: ['accepted', 'agent_compose_run_id', 'agent_compose_status', 'governance_run_id'],
    title: 'GovernanceRunTriggerPublic'
} as const;

export const GovernanceRunsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/GovernanceRunPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        can_trigger: {
            type: 'boolean',
            title: 'Can Trigger'
        },
        ready: {
            type: 'boolean',
            title: 'Ready'
        },
        readiness_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Readiness Code'
        }
    },
    type: 'object',
    required: ['data', 'count', 'can_trigger', 'ready', 'readiness_code'],
    title: 'GovernanceRunsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const ProjectCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['name'],
    title: 'ProjectCreate'
} as const;

export const ProjectMembershipCreateSchema = {
    properties: {
        roles: {
            items: {
                '$ref': '#/components/schemas/ProjectRole'
            },
            type: 'array',
            minItems: 1,
            title: 'Roles'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['roles', 'user_id'],
    title: 'ProjectMembershipCreate'
} as const;

export const ProjectMembershipPublicSchema = {
    properties: {
        roles: {
            items: {
                '$ref': '#/components/schemas/ProjectRole'
            },
            type: 'array',
            minItems: 1,
            title: 'Roles'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        tenant_id: {
            type: 'string',
            format: 'uuid',
            title: 'Tenant Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        revoked_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Revoked At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['roles', 'id', 'tenant_id', 'project_id', 'user_id', 'revoked_at', 'created_at', 'updated_at'],
    title: 'ProjectMembershipPublic'
} as const;

export const ProjectMembershipUpdateSchema = {
    properties: {
        roles: {
            items: {
                '$ref': '#/components/schemas/ProjectRole'
            },
            type: 'array',
            minItems: 1,
            title: 'Roles'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['roles'],
    title: 'ProjectMembershipUpdate'
} as const;

export const ProjectMembershipsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProjectMembershipPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProjectMembershipsPublic'
} as const;

export const ProjectPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        tenant_id: {
            type: 'string',
            format: 'uuid',
            title: 'Tenant Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        archived_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Archived At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'tenant_id', 'created_at', 'updated_at', 'archived_at'],
    title: 'ProjectPublic'
} as const;

export const ProjectRoleSchema = {
    type: 'string',
    enum: ['viewer', 'operator', 'approver'],
    title: 'ProjectRole'
} as const;

export const ProjectUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['name'],
    title: 'ProjectUpdate'
} as const;

export const ProjectsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProjectPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProjectsPublic'
} as const;

export const RunStepPublicSchema = {
    properties: {
        step_code: {
            type: 'string',
            title: 'Step Code'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        attempt: {
            type: 'integer',
            title: 'Attempt'
        },
        input_hash: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Input Hash'
        },
        output_hash: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Output Hash'
        },
        error_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Code'
        },
        started_at: {
            type: 'string',
            format: 'date-time',
            title: 'Started At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        }
    },
    type: 'object',
    required: ['step_code', 'status', 'attempt', 'input_hash', 'output_hash', 'error_code', 'started_at', 'completed_at'],
    title: 'RunStepPublic'
} as const;

export const SourceSnapshotPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        source_type: {
            type: 'string',
            title: 'Source Type'
        },
        content_sha256: {
            type: 'string',
            title: 'Content Sha256'
        },
        schema_fingerprint: {
            type: 'string',
            title: 'Schema Fingerprint'
        },
        method_fingerprint: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Method Fingerprint'
        },
        record_count: {
            type: 'integer',
            title: 'Record Count'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'source_type', 'content_sha256', 'schema_fingerprint', 'method_fingerprint', 'record_count', 'created_at'],
    title: 'SourceSnapshotPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateByAdminSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreateByAdmin'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserUpdateByAdminSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    additionalProperties: false,
    type: 'object',
    title: 'UserUpdateByAdmin'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;