// This file is auto-generated by @hey-api/openapi-ts

export type AuditEventPublic = {
    id: string;
    tenant_id: string;
    project_id: (string | null);
    actor_subject: string;
    actor_type: string;
    action: string;
    target_type: string;
    target_id: string;
    before_data: ({
    [key: string]: unknown;
} | null);
    after_data: ({
    [key: string]: unknown;
} | null);
    ip_address: (string | null);
    occurred_at: string;
    created_at: string;
    updated_at: string;
};

export type AuditEventsPublic = {
    data: Array<AuditEventPublic>;
    count: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type ProjectCreate = {
    name: string;
};

export type ProjectPublic = {
    name: string;
    id: string;
    tenant_id: string;
    created_at: string;
    updated_at: string;
};

export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

export type ProjectUpdate = {
    name: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreateByAdmin = {
    email: string;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdateByAdmin = {
    email?: (string | null);
    is_active?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AuditEventsReadAuditEventsData = {
    limit?: number;
    skip?: number;
};

export type AuditEventsReadAuditEventsResponse = (AuditEventsPublic);

export type HealthHealthLiveResponse = (boolean);

export type HealthHealthReadyResponse = (boolean);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectResponse = (ProjectPublic);

export type ProjectsReadProjectsData = {
    limit?: number;
    skip?: number;
};

export type ProjectsReadProjectsResponse = (ProjectsPublic);

export type ProjectsReadProjectData = {
    projectId: string;
};

export type ProjectsReadProjectResponse = (ProjectPublic);

export type ProjectsRenameProjectData = {
    projectId: string;
    requestBody: ProjectUpdate;
};

export type ProjectsRenameProjectResponse = (ProjectPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreateByAdmin;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdateByAdmin;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);