// This file is auto-generated by @hey-api/openapi-ts

export type AuditEventPublic = {
    id: string;
    tenant_id: string;
    project_id: (string | null);
    actor_subject: string;
    actor_type: string;
    action: string;
    target_type: string;
    target_id: string;
    before_data: ({
    [key: string]: unknown;
} | null);
    after_data: ({
    [key: string]: unknown;
} | null);
    ip_address: (string | null);
    occurred_at: string;
    created_at: string;
    updated_at: string;
};

export type AuditEventsPublic = {
    data: Array<AuditEventPublic>;
    count: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CloudAtlasSourceCreate = {
    instance_id: string;
    capset_id: string;
};

export type CloudAtlasSourcePublic = {
    id: string;
    source_type: string;
    instance_id: string;
    capset_id: string;
    enabled: boolean;
    validation_status: string;
    fingerprint_summary: (string | null);
    created_at: string;
    updated_at: string;
};

export type CloudAtlasSourcesPublic = {
    data: Array<CloudAtlasSourcePublic>;
    count: number;
    can_manage: boolean;
};

export type CloudAtlasSourceUpdate = {
    instance_id: string;
    capset_id: string;
};

export type CloudAtlasSourceValidationRequest = {
    capset_token: string;
};

export type CustomerUploadProfilePublic = {
    required_headers: Array<(string)>;
    warning_headers: Array<(string)>;
    optional_headers: Array<(string)>;
    id: string;
    version: number;
};

export type CustomerUploadPublic = {
    id: string;
    display_filename: string;
    raw_sha256: string;
    record_count: number;
    profile_id: string;
    profile_version: number;
    warnings: Array<CustomerUploadWarningPublic>;
    created_at: string;
};

export type CustomerUploadsPublic = {
    data: Array<CustomerUploadPublic>;
    count: number;
    current_customer_upload_id: (string | null);
    can_upload: boolean;
    can_select: boolean;
};

export type CustomerUploadWarningPublic = {
    code: string;
    field: (string | null);
    count: number;
};

export type FindingDetailPublic = {
    id: string;
    resource_id: string;
    finding_type: string;
    status: string;
    canonical_ip: string;
    first_detected_at: (string | null);
    last_detected_at: (string | null);
    latest_occurrence_at: (string | null);
    latest_transition_at: (string | null);
    occurrence_count: number;
    transition_count: number;
    occurrences?: Array<FindingOccurrencePublic>;
    transitions?: Array<FindingTransitionPublic>;
};

export type FindingOccurrencePublic = {
    id: string;
    governance_run_id: string;
    created_at: string;
    observation_ids?: Array<(string)>;
    source_snapshot_ids?: Array<(string)>;
    source_snapshots?: Array<SourceSnapshotPublic>;
    observations?: Array<IPObservationPublic>;
};

export type FindingPublic = {
    id: string;
    resource_id: string;
    finding_type: string;
    status: string;
    canonical_ip: string;
    first_detected_at: (string | null);
    last_detected_at: (string | null);
    latest_occurrence_at: (string | null);
    latest_transition_at: (string | null);
    occurrence_count: number;
    transition_count: number;
};

export type FindingsPublic = {
    data: Array<FindingPublic>;
    count: number;
    status: string;
    latest_run_id: (string | null);
    latest_run_completed_at: (string | null);
    compatible: boolean;
    compatibility_code: (string | null);
};

export type FindingTransitionPublic = {
    id: string;
    governance_run_id: string;
    transition_type: string;
    created_at: string;
    observation_ids?: Array<(string)>;
    source_snapshot_ids?: Array<(string)>;
    source_snapshots?: Array<SourceSnapshotPublic>;
    observations?: Array<IPObservationPublic>;
};

export type GovernanceRunActionPublic = {
    accepted: boolean;
    action: string;
    governance_run_id: (string | null);
    source_governance_run_id?: (string | null);
    session_id: (string | null);
    agent_compose_run_id: (string | null);
    agent_compose_status: string;
    code?: (string | null);
};

export type GovernanceRunPublic = {
    id: string;
    trigger_id: string;
    session_id: string;
    status: string;
    customer_upload_id: string;
    customer_upload_sha256: string;
    customer_upload_profile_id: string;
    customer_upload_profile_version: number;
    source_instance_id: string;
    cloudatlas_validated_fingerprint: string;
    cloudatlas_capset_id: string;
    cloudatlas_method: string;
    package_sha256: string;
    descriptor_sha256: string;
    runner_build_version: string;
    processing_contract_version: (string | null);
    created_at: string;
    completed_at: (string | null);
    session_terminal_at: (string | null);
    session_recovery_code: (string | null);
    steps: Array<RunStepPublic>;
    snapshots: Array<SourceSnapshotPublic>;
    reused_snapshot_count?: number;
    can_retry?: boolean;
    can_rerun?: boolean;
    blocking_code?: (string | null);
};

export type GovernanceRunsPublic = {
    data: Array<GovernanceRunPublic>;
    count: number;
    can_trigger: boolean;
    ready: boolean;
    readiness_code: (string | null);
    launch_blocking_code?: (string | null);
};

export type GovernanceRunTriggerPublic = {
    accepted: boolean;
    agent_compose_run_id: string;
    agent_compose_status: string;
    governance_run_id: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type IPAssetDetailPublic = {
    id: string;
    resource_id: string;
    resource_type: string;
    canonical_key: string;
    canonical_ip: string;
    customer_observation_count: number;
    cloudatlas_observation_count: number;
    observation_count: number;
    customer_observed: boolean;
    cloudatlas_observed: boolean;
    open_finding_id: (string | null);
    open_finding_type: (string | null);
    observations?: Array<IPObservationPublic>;
};

export type IPAssetPublic = {
    id: string;
    resource_id: string;
    resource_type: string;
    canonical_key: string;
    canonical_ip: string;
    customer_observation_count: number;
    cloudatlas_observation_count: number;
    observation_count: number;
    customer_observed: boolean;
    cloudatlas_observed: boolean;
    open_finding_id: (string | null);
    open_finding_type: (string | null);
};

export type IPAssetsPublic = {
    data: Array<IPAssetPublic>;
    count: number;
    latest_run_id: (string | null);
    latest_run_completed_at: (string | null);
    compatible: boolean;
    compatibility_code: (string | null);
};

export type IPObservationPublic = {
    id: string;
    source_type: string;
    source_record_key: string;
    raw_ip: string;
    canonical_ip: string;
    cloudatlas_asset_id: (string | null);
    cloudatlas_status: (string | null);
    source_snapshot_id: string;
};

export type Message = {
    message: string;
};

export type ProjectCreate = {
    name: string;
};

export type ProjectMembershipCreate = {
    roles: Array<ProjectRole>;
    user_id: string;
};

export type ProjectMembershipPublic = {
    roles: Array<ProjectRole>;
    id: string;
    tenant_id: string;
    project_id: string;
    user_id: string;
    revoked_at: (string | null);
    created_at: string;
    updated_at: string;
};

export type ProjectMembershipsPublic = {
    data: Array<ProjectMembershipPublic>;
    count: number;
};

export type ProjectMembershipUpdate = {
    roles: Array<ProjectRole>;
};

export type ProjectPublic = {
    name: string;
    id: string;
    tenant_id: string;
    created_at: string;
    updated_at: string;
    archived_at: (string | null);
};

export type ProjectRole = 'viewer' | 'operator' | 'approver';

export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

export type ProjectUpdate = {
    name: string;
};

export type RunStepPublic = {
    step_code: string;
    status: string;
    attempt: number;
    input_hash: (string | null);
    output_hash: (string | null);
    error_code: (string | null);
    started_at: string;
    completed_at: (string | null);
};

export type SourceSnapshotPublic = {
    id: string;
    source_type: string;
    content_sha256: string;
    schema_fingerprint: string;
    method_fingerprint: (string | null);
    record_count: number;
    created_at: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreateByAdmin = {
    email: string;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdateByAdmin = {
    email?: (string | null);
    is_active?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AuditEventsReadAuditEventsData = {
    limit?: number;
    skip?: number;
};

export type AuditEventsReadAuditEventsResponse = (AuditEventsPublic);

export type CloudatlasSourceInstancesReadCloudatlasSourcesData = {
    projectId: string;
};

export type CloudatlasSourceInstancesReadCloudatlasSourcesResponse = (CloudAtlasSourcesPublic);

export type CloudatlasSourceInstancesCreateCloudatlasSourceData = {
    projectId: string;
    requestBody: CloudAtlasSourceCreate;
};

export type CloudatlasSourceInstancesCreateCloudatlasSourceResponse = (CloudAtlasSourcePublic);

export type CloudatlasSourceInstancesUpdateCloudatlasSourceData = {
    projectId: string;
    requestBody: CloudAtlasSourceUpdate;
    sourceId: string;
};

export type CloudatlasSourceInstancesUpdateCloudatlasSourceResponse = (CloudAtlasSourcePublic);

export type CloudatlasSourceInstancesValidateCloudatlasSourceData = {
    projectId: string;
    requestBody: CloudAtlasSourceValidationRequest;
    sourceId: string;
};

export type CloudatlasSourceInstancesValidateCloudatlasSourceResponse = (CloudAtlasSourcePublic);

export type CloudatlasSourceInstancesEnableCloudatlasSourceData = {
    projectId: string;
    sourceId: string;
};

export type CloudatlasSourceInstancesEnableCloudatlasSourceResponse = (CloudAtlasSourcePublic);

export type CloudatlasSourceInstancesDisableCloudatlasSourceData = {
    projectId: string;
    sourceId: string;
};

export type CloudatlasSourceInstancesDisableCloudatlasSourceResponse = (CloudAtlasSourcePublic);

export type GovernanceRunsReadGovernanceRunsData = {
    projectId: string;
};

export type GovernanceRunsReadGovernanceRunsResponse = (GovernanceRunsPublic);

export type GovernanceRunsTriggerGovernanceRunData = {
    idempotencyKey?: (string | null);
    projectId: string;
};

export type GovernanceRunsTriggerGovernanceRunResponse = (GovernanceRunTriggerPublic);

export type GovernanceRunsRetryGovernanceRunData = {
    projectId: string;
    runId: string;
};

export type GovernanceRunsRetryGovernanceRunResponse = (GovernanceRunActionPublic);

export type GovernanceRunsRerunGovernanceRunData = {
    idempotencyKey?: (string | null);
    projectId: string;
    runId: string;
};

export type GovernanceRunsRerunGovernanceRunResponse = (GovernanceRunActionPublic);

export type HealthHealthLiveResponse = (boolean);

export type HealthHealthReadyResponse = (boolean);

export type IpResultsReadIpAssetsData = {
    limit?: number;
    projectId: string;
    skip?: number;
};

export type IpResultsReadIpAssetsResponse = (IPAssetsPublic);

export type IpResultsReadIpAssetData = {
    projectId: string;
    resourceId: string;
};

export type IpResultsReadIpAssetResponse = (IPAssetDetailPublic);

export type IpResultsReadFindingsData = {
    limit?: number;
    projectId: string;
    skip?: number;
    status?: string;
};

export type IpResultsReadFindingsResponse = (FindingsPublic);

export type IpResultsReadFindingData = {
    findingId: string;
    projectId: string;
    traceLimit?: number;
};

export type IpResultsReadFindingResponse = (FindingDetailPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type ProjectMembershipsReadProjectMembershipsData = {
    limit?: number;
    projectId: string;
    skip?: number;
};

export type ProjectMembershipsReadProjectMembershipsResponse = (ProjectMembershipsPublic);

export type ProjectMembershipsGrantProjectMembershipData = {
    projectId: string;
    requestBody: ProjectMembershipCreate;
};

export type ProjectMembershipsGrantProjectMembershipResponse = (ProjectMembershipPublic);

export type ProjectMembershipsChangeProjectMembershipRolesData = {
    membershipId: string;
    projectId: string;
    requestBody: ProjectMembershipUpdate;
};

export type ProjectMembershipsChangeProjectMembershipRolesResponse = (ProjectMembershipPublic);

export type ProjectMembershipsRevokeProjectMembershipData = {
    membershipId: string;
    projectId: string;
};

export type ProjectMembershipsRevokeProjectMembershipResponse = (ProjectMembershipPublic);

export type ProjectMembershipsRegrantProjectMembershipData = {
    membershipId: string;
    projectId: string;
    requestBody: ProjectMembershipUpdate;
};

export type ProjectMembershipsRegrantProjectMembershipResponse = (ProjectMembershipPublic);

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectResponse = (ProjectPublic);

export type ProjectsReadProjectsData = {
    limit?: number;
    skip?: number;
};

export type ProjectsReadProjectsResponse = (ProjectsPublic);

export type ProjectsReadProjectData = {
    projectId: string;
};

export type ProjectsReadProjectResponse = (ProjectPublic);

export type ProjectsRenameProjectData = {
    projectId: string;
    requestBody: ProjectUpdate;
};

export type ProjectsRenameProjectResponse = (ProjectPublic);

export type ProjectsReadCurrentCustomerUploadProfileData = {
    projectId: string;
};

export type ProjectsReadCurrentCustomerUploadProfileResponse = (CustomerUploadProfilePublic);

export type ProjectsCreateCustomerUploadData = {
    formData: {
        file: (Blob | File);
    };
    projectId: string;
};

export type ProjectsCreateCustomerUploadResponse = (CustomerUploadPublic);

export type ProjectsReadCustomerUploadsData = {
    limit?: number;
    projectId: string;
    skip?: number;
};

export type ProjectsReadCustomerUploadsResponse = (CustomerUploadsPublic);

export type ProjectsDeleteCustomerUploadData = {
    projectId: string;
    uploadId: string;
};

export type ProjectsDeleteCustomerUploadResponse = (void);

export type ProjectsSelectCurrentCustomerUploadData = {
    projectId: string;
    uploadId: string;
};

export type ProjectsSelectCurrentCustomerUploadResponse = (CustomerUploadPublic);

export type ProjectsArchiveProjectData = {
    projectId: string;
};

export type ProjectsArchiveProjectResponse = (ProjectPublic);

export type ProjectsReactivateProjectData = {
    projectId: string;
};

export type ProjectsReactivateProjectResponse = (ProjectPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreateByAdmin;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdateByAdmin;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);