"""Customer ledger revisions and derived input provenance

Revision ID: 4d1984a506cc
Revises: c5d6e7f8a9b0
Create Date: 2026-09-15 10:30:03.742102

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d1984a506cc'
down_revision = 'c5d6e7f8a9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_ledger_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('parent_revision_id', sa.Uuid(), nullable=True),
    sa.Column('base_upload_id', sa.Uuid(), nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('operation_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('request_sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('input_changed', sa.Boolean(), nullable=False),
    sa.Column('sealed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("request_sha256 ~ '^[0-9a-f]{64}$'", name='ck_customer_ledger_request_hash'),
    sa.ForeignKeyConstraint(['base_upload_id', 'project_id', 'tenant_id'], ['customer_uploads.id', 'customer_uploads.project_id', 'customer_uploads.tenant_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_revision_id', 'project_id', 'tenant_id'], ['customer_ledger_revisions.id', 'customer_ledger_revisions.project_id', 'customer_ledger_revisions.tenant_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'tenant_id'], ['projects.id', 'projects.tenant_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['upload_id', 'project_id', 'tenant_id'], ['customer_uploads.id', 'customer_uploads.project_id', 'customer_uploads.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'project_id', 'tenant_id', name='uq_customer_ledger_revision_scope'),
    sa.UniqueConstraint('project_id', 'created_by', 'operation_key', name='uq_customer_ledger_operation')
    )
    op.create_index(op.f('ix_customer_ledger_revisions_project_id'), 'customer_ledger_revisions', ['project_id'], unique=False)
    op.create_table('customer_ledger_entry_versions',
    sa.Column('revision_id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('canonical_ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('management', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.CheckConstraint('position > 0', name='ck_customer_ledger_position'),
    sa.ForeignKeyConstraint(['revision_id'], ['customer_ledger_revisions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('revision_id', 'entry_id'),
    sa.UniqueConstraint('revision_id', 'position', name='uq_customer_ledger_position')
    )
    op.create_index(op.f('ix_customer_ledger_entry_versions_canonical_ip'), 'customer_ledger_entry_versions', ['canonical_ip'], unique=False)
    op.add_column('projects', sa.Column('current_customer_ledger_revision_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_projects_current_customer_ledger', 'projects', 'customer_ledger_revisions', ['current_customer_ledger_revision_id', 'id', 'tenant_id'], ['id', 'project_id', 'tenant_id'], ondelete='RESTRICT', use_alter=True)
    op.execute("""
        CREATE FUNCTION guard_customer_ledger_revision() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_OP = 'UPDATE' AND NOT OLD.sealed AND NEW.sealed
             AND (to_jsonb(OLD) - 'sealed') = (to_jsonb(NEW) - 'sealed') THEN
            RETURN NEW;
          END IF;
          RAISE EXCEPTION 'customer ledger revision is immutable';
        END $$;
        CREATE TRIGGER customer_ledger_revision_immutable BEFORE UPDATE OR DELETE ON customer_ledger_revisions
          FOR EACH ROW EXECUTE FUNCTION guard_customer_ledger_revision();
        CREATE FUNCTION guard_customer_ledger_entry() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE frozen boolean;
        BEGIN
          IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION 'customer ledger entry is immutable'; END IF;
          SELECT sealed INTO frozen FROM customer_ledger_revisions WHERE id = NEW.revision_id FOR SHARE;
          IF frozen IS DISTINCT FROM false THEN RAISE EXCEPTION 'customer ledger revision is sealed'; END IF;
          RETURN NEW;
        END $$;
        CREATE TRIGGER customer_ledger_entry_immutable BEFORE INSERT OR UPDATE OR DELETE ON customer_ledger_entry_versions
          FOR EACH ROW EXECUTE FUNCTION guard_customer_ledger_entry();
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_projects_current_customer_ledger', 'projects', type_='foreignkey')
    op.drop_column('projects', 'current_customer_ledger_revision_id')
    op.drop_index(op.f('ix_customer_ledger_entry_versions_canonical_ip'), table_name='customer_ledger_entry_versions')
    op.drop_table('customer_ledger_entry_versions')
    op.drop_index(op.f('ix_customer_ledger_revisions_project_id'), table_name='customer_ledger_revisions')
    op.drop_table('customer_ledger_revisions')
    op.execute('DROP FUNCTION guard_customer_ledger_entry()')
    op.execute('DROP FUNCTION guard_customer_ledger_revision()')
    # ### end Alembic commands ###
