"""cloudatlas ledger local revisions

Revision ID: 6ed2962462de
Revises: 4d1984a506cc
Create Date: 2026-09-15 14:38:21.926065

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ed2962462de'
down_revision = '4d1984a506cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloudatlas_ledger_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('governance_run_id', sa.Uuid(), nullable=False),
    sa.Column('source_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('observation_id', sa.Uuid(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('followed', sa.Boolean(), nullable=False),
    sa.Column('scope_state', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('operation_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('request_sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(kind = 'management' AND observation_id IS NOT NULL AND scope_state IS NULL) OR (kind = 'scope' AND observation_id IS NULL AND scope_state IN ('UNKNOWN','SEPARATE','CONFIRMED_LEGACY'))", name='ck_cloud_ledger_kind'),
    sa.CheckConstraint("request_sha256 ~ '^[0-9a-f]{64}$'", name='ck_cloud_ledger_request_hash'),
    sa.CheckConstraint('revision > 0', name='ck_cloud_ledger_revision'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['observation_id', 'governance_run_id', 'project_id', 'tenant_id'], ['observations.id', 'observations.governance_run_id', 'observations.project_id', 'observations.tenant_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_snapshot_id', 'governance_run_id', 'project_id', 'tenant_id'], ['source_snapshots.id', 'source_snapshots.governance_run_id', 'source_snapshots.project_id', 'source_snapshots.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'created_by', 'operation_key', name='uq_cloud_ledger_operation'),
    sa.UniqueConstraint('source_snapshot_id', 'revision', name='uq_cloud_ledger_revision')
    )
    op.create_index(op.f('ix_cloudatlas_ledger_revisions_observation_id'), 'cloudatlas_ledger_revisions', ['observation_id'], unique=False)
    op.create_index(op.f('ix_cloudatlas_ledger_revisions_project_id'), 'cloudatlas_ledger_revisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_cloudatlas_ledger_revisions_source_snapshot_id'), 'cloudatlas_ledger_revisions', ['source_snapshot_id'], unique=False)
    op.execute("""
        CREATE FUNCTION guard_cloud_ledger_revision() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'cloudatlas ledger revision is immutable';
        END $$;
        CREATE TRIGGER cloud_ledger_revision_immutable BEFORE UPDATE OR DELETE ON cloudatlas_ledger_revisions
          FOR EACH ROW EXECUTE FUNCTION guard_cloud_ledger_revision();
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cloudatlas_ledger_revisions_source_snapshot_id'), table_name='cloudatlas_ledger_revisions')
    op.drop_index(op.f('ix_cloudatlas_ledger_revisions_project_id'), table_name='cloudatlas_ledger_revisions')
    op.drop_index(op.f('ix_cloudatlas_ledger_revisions_observation_id'), table_name='cloudatlas_ledger_revisions')
    op.drop_table('cloudatlas_ledger_revisions')
    op.execute('DROP FUNCTION guard_cloud_ledger_revision()')
    # ### end Alembic commands ###
