"""Model connection versions and protected credentials

Revision ID: c5d6e7f8a9b0
Revises: b4c5d6e7f8a9
Create Date: 2026-09-12 18:57:58.017051

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5d6e7f8a9b0'
down_revision = 'b4c5d6e7f8a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_connection_secrets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('key_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('octet_length(nonce) = 12 AND octet_length(ciphertext) >= 16', name='ck_model_connection_secret_cipher'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_id', 'nonce', name='uq_model_connection_secret_nonce')
    )
    op.create_table('model_connection_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('secret_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('protocol', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('model_identity', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('resolved_address', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('runner_build_version', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('runtime_version', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('runtime_project_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('runtime_spec_hash', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('runtime_project_id', sa.String(length=64), nullable=True),
    sa.Column('runtime_project_revision', sa.String(length=30), nullable=True),
    sa.Column('runtime_agents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('validation_operation_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("protocol IN ('responses', 'chat_completions')", name='ck_model_connection_protocol'),
    sa.CheckConstraint("validation_status IN ('UNVERIFIED', 'VALIDATING', 'VALIDATED', 'FAILED', 'ACTIVATING')", name='ck_model_connection_validation_status'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['secret_id'], ['model_connection_secrets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secret_id', name='uq_model_connection_version_secret')
    )
    op.create_table('model_connection_leases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('family', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('token_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('token_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('key_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_requests', sa.Integer(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.CheckConstraint("family IN ('validation', 'investigation', 'report')", name='ck_model_connection_lease_family'),
    sa.CheckConstraint("purpose IN ('qualification', 'investigation', 'analysis_report')", name='ck_model_connection_lease_purpose'),
    sa.CheckConstraint('request_count >= 0 AND max_requests > 0 AND request_count <= max_requests', name='ck_model_connection_lease_budget'),
    sa.ForeignKeyConstraint(['connection_id'], ['model_connection_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family', 'task_id', 'purpose', name='uq_model_connection_lease_task')
    )
    op.create_table('model_connection_operations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('request_fingerprint', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('key_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('expected_generation', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('agent_run_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("action IN ('SAVE', 'ADOPT', 'VALIDATE', 'ACTIVATE', 'REVOKE', 'DISCARD')", name='ck_model_connection_operation_action'),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'UNKNOWN', 'SUCCEEDED', 'FAILED')", name='ck_model_connection_operation_status'),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['connection_id'], ['model_connection_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'actor_id', 'action', 'idempotency_key', name='uq_model_connection_operation_intent')
    )
    op.create_table('model_connection_states',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('active_id', sa.Uuid(), nullable=True),
    sa.Column('pending_id', sa.Uuid(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('adopted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('generation >= 0', name='ck_model_connection_generation'),
    sa.ForeignKeyConstraint(['active_id'], ['model_connection_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pending_id'], ['model_connection_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.add_column('ai_investigations', sa.Column('connection_version_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_ai_investigations_connection_version_id'), 'ai_investigations', ['connection_version_id'], unique=False)
    op.create_foreign_key('fk_ai_investigations_model_connection', 'ai_investigations', 'model_connection_versions', ['connection_version_id'], ['id'], ondelete='RESTRICT')
    op.add_column('analysis_reports', sa.Column('connection_version_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_analysis_reports_connection_version_id'), 'analysis_reports', ['connection_version_id'], unique=False)
    op.create_foreign_key('fk_analysis_reports_model_connection', 'analysis_reports', 'model_connection_versions', ['connection_version_id'], ['id'], ondelete='RESTRICT')
    op.add_column('ai_governance_drafts', sa.Column('connection_version_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_ai_governance_drafts_connection_version_id'), 'ai_governance_drafts', ['connection_version_id'], unique=False)
    op.create_foreign_key('fk_ai_governance_drafts_model_connection', 'ai_governance_drafts', 'model_connection_versions', ['connection_version_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_ai_governance_drafts_model_connection', 'ai_governance_drafts', type_='foreignkey')
    op.drop_index(op.f('ix_ai_governance_drafts_connection_version_id'), table_name='ai_governance_drafts')
    op.drop_column('ai_governance_drafts', 'connection_version_id')
    op.drop_constraint('fk_analysis_reports_model_connection', 'analysis_reports', type_='foreignkey')
    op.drop_index(op.f('ix_analysis_reports_connection_version_id'), table_name='analysis_reports')
    op.drop_column('analysis_reports', 'connection_version_id')
    op.drop_constraint('fk_ai_investigations_model_connection', 'ai_investigations', type_='foreignkey')
    op.drop_index(op.f('ix_ai_investigations_connection_version_id'), table_name='ai_investigations')
    op.drop_column('ai_investigations', 'connection_version_id')
    op.drop_table('model_connection_states')
    op.drop_table('model_connection_operations')
    op.drop_table('model_connection_leases')
    op.drop_table('model_connection_versions')
    op.drop_table('model_connection_secrets')
    # ### end Alembic commands ###
