/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutAiSettingsRouteImport } from './routes/_layout/ai-settings'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutProjectsProjectIdNetflowLedgerRouteImport } from './routes/_layout/projects.$projectId.netflow-ledger'
import { Route as LayoutProjectsProjectIdCustomerLedgerRouteImport } from './routes/_layout/projects.$projectId.customer-ledger'
import { Route as LayoutProjectsProjectIdCloudatlasLedgerRouteImport } from './routes/_layout/projects.$projectId.cloudatlas-ledger'
import { Route as LayoutProjectsProjectIdRunsRunIdLineageRouteImport } from './routes/_layout/projects.$projectId.runs.$runId.lineage'
import { Route as LayoutProjectsProjectIdRunsRunIdComparisonRouteImport } from './routes/_layout/projects.$projectId.runs.$runId.comparison'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAiSettingsRoute = LayoutAiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsProjectIdNetflowLedgerRoute =
  LayoutProjectsProjectIdNetflowLedgerRouteImport.update({
    id: '/projects/$projectId/netflow-ledger',
    path: '/projects/$projectId/netflow-ledger',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProjectsProjectIdCustomerLedgerRoute =
  LayoutProjectsProjectIdCustomerLedgerRouteImport.update({
    id: '/projects/$projectId/customer-ledger',
    path: '/projects/$projectId/customer-ledger',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProjectsProjectIdCloudatlasLedgerRoute =
  LayoutProjectsProjectIdCloudatlasLedgerRouteImport.update({
    id: '/projects/$projectId/cloudatlas-ledger',
    path: '/projects/$projectId/cloudatlas-ledger',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProjectsProjectIdRunsRunIdLineageRoute =
  LayoutProjectsProjectIdRunsRunIdLineageRouteImport.update({
    id: '/projects/$projectId/runs/$runId/lineage',
    path: '/projects/$projectId/runs/$runId/lineage',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProjectsProjectIdRunsRunIdComparisonRoute =
  LayoutProjectsProjectIdRunsRunIdComparisonRouteImport.update({
    id: '/projects/$projectId/runs/$runId/comparison',
    path: '/projects/$projectId/runs/$runId/comparison',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof LayoutAdminRoute
  '/ai-settings': typeof LayoutAiSettingsRoute
  '/settings': typeof LayoutSettingsRoute
  '/projects/$projectId/cloudatlas-ledger': typeof LayoutProjectsProjectIdCloudatlasLedgerRoute
  '/projects/$projectId/customer-ledger': typeof LayoutProjectsProjectIdCustomerLedgerRoute
  '/projects/$projectId/netflow-ledger': typeof LayoutProjectsProjectIdNetflowLedgerRoute
  '/projects/$projectId/runs/$runId/comparison': typeof LayoutProjectsProjectIdRunsRunIdComparisonRoute
  '/projects/$projectId/runs/$runId/lineage': typeof LayoutProjectsProjectIdRunsRunIdLineageRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof LayoutAdminRoute
  '/ai-settings': typeof LayoutAiSettingsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/projects/$projectId/cloudatlas-ledger': typeof LayoutProjectsProjectIdCloudatlasLedgerRoute
  '/projects/$projectId/customer-ledger': typeof LayoutProjectsProjectIdCustomerLedgerRoute
  '/projects/$projectId/netflow-ledger': typeof LayoutProjectsProjectIdNetflowLedgerRoute
  '/projects/$projectId/runs/$runId/comparison': typeof LayoutProjectsProjectIdRunsRunIdComparisonRoute
  '/projects/$projectId/runs/$runId/lineage': typeof LayoutProjectsProjectIdRunsRunIdLineageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/ai-settings': typeof LayoutAiSettingsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/projects/$projectId/cloudatlas-ledger': typeof LayoutProjectsProjectIdCloudatlasLedgerRoute
  '/_layout/projects/$projectId/customer-ledger': typeof LayoutProjectsProjectIdCustomerLedgerRoute
  '/_layout/projects/$projectId/netflow-ledger': typeof LayoutProjectsProjectIdNetflowLedgerRoute
  '/_layout/projects/$projectId/runs/$runId/comparison': typeof LayoutProjectsProjectIdRunsRunIdComparisonRoute
  '/_layout/projects/$projectId/runs/$runId/lineage': typeof LayoutProjectsProjectIdRunsRunIdLineageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/ai-settings'
    | '/settings'
    | '/projects/$projectId/cloudatlas-ledger'
    | '/projects/$projectId/customer-ledger'
    | '/projects/$projectId/netflow-ledger'
    | '/projects/$projectId/runs/$runId/comparison'
    | '/projects/$projectId/runs/$runId/lineage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/ai-settings'
    | '/settings'
    | '/'
    | '/projects/$projectId/cloudatlas-ledger'
    | '/projects/$projectId/customer-ledger'
    | '/projects/$projectId/netflow-ledger'
    | '/projects/$projectId/runs/$runId/comparison'
    | '/projects/$projectId/runs/$runId/lineage'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/admin'
    | '/_layout/ai-settings'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/projects/$projectId/cloudatlas-ledger'
    | '/_layout/projects/$projectId/customer-ledger'
    | '/_layout/projects/$projectId/netflow-ledger'
    | '/_layout/projects/$projectId/runs/$runId/comparison'
    | '/_layout/projects/$projectId/runs/$runId/lineage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ai-settings': {
      id: '/_layout/ai-settings'
      path: '/ai-settings'
      fullPath: '/ai-settings'
      preLoaderRoute: typeof LayoutAiSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$projectId/netflow-ledger': {
      id: '/_layout/projects/$projectId/netflow-ledger'
      path: '/projects/$projectId/netflow-ledger'
      fullPath: '/projects/$projectId/netflow-ledger'
      preLoaderRoute: typeof LayoutProjectsProjectIdNetflowLedgerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$projectId/customer-ledger': {
      id: '/_layout/projects/$projectId/customer-ledger'
      path: '/projects/$projectId/customer-ledger'
      fullPath: '/projects/$projectId/customer-ledger'
      preLoaderRoute: typeof LayoutProjectsProjectIdCustomerLedgerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$projectId/cloudatlas-ledger': {
      id: '/_layout/projects/$projectId/cloudatlas-ledger'
      path: '/projects/$projectId/cloudatlas-ledger'
      fullPath: '/projects/$projectId/cloudatlas-ledger'
      preLoaderRoute: typeof LayoutProjectsProjectIdCloudatlasLedgerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$projectId/runs/$runId/lineage': {
      id: '/_layout/projects/$projectId/runs/$runId/lineage'
      path: '/projects/$projectId/runs/$runId/lineage'
      fullPath: '/projects/$projectId/runs/$runId/lineage'
      preLoaderRoute: typeof LayoutProjectsProjectIdRunsRunIdLineageRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$projectId/runs/$runId/comparison': {
      id: '/_layout/projects/$projectId/runs/$runId/comparison'
      path: '/projects/$projectId/runs/$runId/comparison'
      fullPath: '/projects/$projectId/runs/$runId/comparison'
      preLoaderRoute: typeof LayoutProjectsProjectIdRunsRunIdComparisonRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAiSettingsRoute: typeof LayoutAiSettingsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProjectsProjectIdCloudatlasLedgerRoute: typeof LayoutProjectsProjectIdCloudatlasLedgerRoute
  LayoutProjectsProjectIdCustomerLedgerRoute: typeof LayoutProjectsProjectIdCustomerLedgerRoute
  LayoutProjectsProjectIdNetflowLedgerRoute: typeof LayoutProjectsProjectIdNetflowLedgerRoute
  LayoutProjectsProjectIdRunsRunIdComparisonRoute: typeof LayoutProjectsProjectIdRunsRunIdComparisonRoute
  LayoutProjectsProjectIdRunsRunIdLineageRoute: typeof LayoutProjectsProjectIdRunsRunIdLineageRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAiSettingsRoute: LayoutAiSettingsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProjectsProjectIdCloudatlasLedgerRoute:
    LayoutProjectsProjectIdCloudatlasLedgerRoute,
  LayoutProjectsProjectIdCustomerLedgerRoute:
    LayoutProjectsProjectIdCustomerLedgerRoute,
  LayoutProjectsProjectIdNetflowLedgerRoute:
    LayoutProjectsProjectIdNetflowLedgerRoute,
  LayoutProjectsProjectIdRunsRunIdComparisonRoute:
    LayoutProjectsProjectIdRunsRunIdComparisonRoute,
  LayoutProjectsProjectIdRunsRunIdLineageRoute:
    LayoutProjectsProjectIdRunsRunIdLineageRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
