#!/bin/sh
set -eu

: "${DOCKER_IMAGE_RUNNER:?DOCKER_IMAGE_RUNNER is required}"
: "${RUNNER_BUILD_VERSION:?RUNNER_BUILD_VERSION is required}"
: "${GOVERNANCE_RUNNER_BUILD_VERSION:=${RUNNER_BUILD_VERSION}}"
export GOVERNANCE_RUNNER_BUILD_VERSION
: "${ARTIFACT_HOST_PATH:?ARTIFACT_HOST_PATH is required}"

input=${1:?input template is required}
output=${2:?output path is required}
export CLOUDATLAS_ASSETS_CAPSET_TOKEN="${CLOUDATLAS_ASSETS_CAPSET_TOKEN:-}"
export CLOUDATLAS_ROOT_DOMAINS_CAPSET_TOKEN="${CLOUDATLAS_ROOT_DOMAINS_CAPSET_TOKEN:-}"
export CLOUDATLAS_DNS_CAPSET_TOKEN="${CLOUDATLAS_DNS_CAPSET_TOKEN:-}"
export CLOUDATLAS_SUBDOMAIN_CAPSET_TOKEN="${CLOUDATLAS_SUBDOMAIN_CAPSET_TOKEN:-}"
export CLOUDATLAS_CERT_CAPSET_TOKEN="${CLOUDATLAS_CERT_CAPSET_TOKEN:-}"
export CLOUDATLAS_OPENPORT_CAPSET_TOKEN="${CLOUDATLAS_OPENPORT_CAPSET_TOKEN:-}"
export CLOUDATLAS_WEB_CAPSET_TOKEN="${CLOUDATLAS_WEB_CAPSET_TOKEN:-}"
export CLOUDATLAS_DIR_CAPSET_TOKEN="${CLOUDATLAS_DIR_CAPSET_TOKEN:-}"
export CLOUDATLAS_APPFINGER_CAPSET_TOKEN="${CLOUDATLAS_APPFINGER_CAPSET_TOKEN:-}"
export CLOUDATLAS_CRAWLER_CAPSET_TOKEN="${CLOUDATLAS_CRAWLER_CAPSET_TOKEN:-}"
export CLOUDATLAS_SEED_ENTERPRISE_CAPSET_TOKEN="${CLOUDATLAS_SEED_ENTERPRISE_CAPSET_TOKEN:-}"
export CLOUDATLAS_SEED_KEYWORD_CAPSET_TOKEN="${CLOUDATLAS_SEED_KEYWORD_CAPSET_TOKEN:-}"
export CLOUDATLAS_SEED_DOMAIN_CAPSET_TOKEN="${CLOUDATLAS_SEED_DOMAIN_CAPSET_TOKEN:-}"
export CLOUDATLAS_SEED_EMAIL_CAPSET_TOKEN="${CLOUDATLAS_SEED_EMAIL_CAPSET_TOKEN:-}"
export CLOUDATLAS_SEED_CERT_CAPSET_TOKEN="${CLOUDATLAS_SEED_CERT_CAPSET_TOKEN:-}"
export CLOUDATLAS_SEED_ICON_CAPSET_TOKEN="${CLOUDATLAS_SEED_ICON_CAPSET_TOKEN:-}"
export CLOUDATLAS_SEED_TITLE_CAPSET_TOKEN="${CLOUDATLAS_SEED_TITLE_CAPSET_TOKEN:-}"
export MODEL_QUALIFICATION_ALLOW_BAIZHI_TEST="${MODEL_QUALIFICATION_ALLOW_BAIZHI_TEST:-false}"
export AI_INVESTIGATION_ALLOW_BAIZHI_TEST="${AI_INVESTIGATION_ALLOW_BAIZHI_TEST:-false}"
export AI_INVESTIGATION_SYNTHETIC_MANIFEST="${AI_INVESTIGATION_SYNTHETIC_MANIFEST:-[]}"
export AI_INVESTIGATION_TIMEOUT_SECONDS="${AI_INVESTIGATION_TIMEOUT_SECONDS:-120}"
export AI_INVESTIGATION_FOLLOWUP_TIMEOUT_SECONDS="${AI_INVESTIGATION_FOLLOWUP_TIMEOUT_SECONDS:-120}"
export AI_INVESTIGATION_MAX_TOOL_CALLS="${AI_INVESTIGATION_MAX_TOOL_CALLS:-4}"
export AI_INVESTIGATION_MAX_MATERIAL_BYTES="${AI_INVESTIGATION_MAX_MATERIAL_BYTES:-65536}"
export AI_INVESTIGATION_MAX_OUTPUT_BYTES="${AI_INVESTIGATION_MAX_OUTPUT_BYTES:-32768}"
export AI_ANALYSIS_REPORT_ALLOW_BAIZHI_TEST="${AI_ANALYSIS_REPORT_ALLOW_BAIZHI_TEST:-false}"
export AI_ANALYSIS_REPORT_SYNTHETIC_MANIFEST="${AI_ANALYSIS_REPORT_SYNTHETIC_MANIFEST:-[]}"
export AI_ANALYSIS_REPORT_TIMEOUT_SECONDS="${AI_ANALYSIS_REPORT_TIMEOUT_SECONDS:-120}"
export AI_ANALYSIS_REPORT_MAX_TOOL_CALLS="${AI_ANALYSIS_REPORT_MAX_TOOL_CALLS:-4}"
export AI_ANALYSIS_REPORT_MAX_MATERIAL_BYTES="${AI_ANALYSIS_REPORT_MAX_MATERIAL_BYTES:-65536}"
export AI_ANALYSIS_REPORT_MAX_OUTPUT_BYTES="${AI_ANALYSIS_REPORT_MAX_OUTPUT_BYTES:-32768}"

awk '
function render(text, token, name, at) {
  while (match(text, /\$\{[A-Z][A-Z0-9_]*\}/)) {
    at = RSTART
    token = substr(text, at, RLENGTH)
    name = substr(token, 3, length(token) - 3)
    if (!(name in ENVIRON)) {
      print name " is required" > "/dev/stderr"
      exit 1
    }
    text = substr(text, 1, at - 1) ENVIRON[name] substr(text, at + length(token))
  }
  return text
}
{ print render($0) }
' "$input" > "$output"
