export const businessLabels: Record<string, string> = Object.setPrototypeOf(
  {
    SOURCE: "来源",
    SNAPSHOT: "快照",
    PROCESS: "处理合同",
    COMPARISON: "比较结果",
    FINDING: "发现项事件",
    REPORT: "报告",
    CUSTOMER_UPLOAD: "客户上传",
    CustomerUpload: "客户上传",
    CLOUDATLAS: "CloudAtlas 来源",
    NETFLOW: "NetFlow 来源",
    PRESENT: "已固定来源快照，包括零记录快照",
    ABSENT: "未提供输入",
    ACTIVE: "已观测到有效活动",
    UNKNOWN: "无有效活动证据，不代表零流量或零风险",
    EMPTY: "当前范围无可展示的比较或发现项事件，不代表零风险",
    PARTIAL: "投影已截断，不代表发布失败",
    COMPLETE: "投影未截断，不代表输入覆盖完整或零风险",
    matched: "客户上传与 CloudAtlas 均已观测",
    customer_upload_only: "仅客户上传已观测",
    cloudatlas_only: "仅 CloudAtlas 已观测",
    neither_source_observed: "两个来源均未观测",
    observed_in_both_sources: "两个来源均已观测",
    observed_in_customer_upload_only: "仅客户上传已观测",
    observed_in_cloudatlas_only: "仅 CloudAtlas 已观测",
    not_observed_in_either_source: "两个来源均未观测",
    positive_activity_observed: "已观测到有效活动",
    positive_activity_evidence: "存在有效活动证据",
    no_positive_activity_evidence: "没有有效活动证据，不代表零流量或零风险",
    netflow_input_absent: "未提供 NetFlow 输入",
    comparison_limit: "比较结果达到返回上限",
    finding_limit: "发现项事件达到返回上限",
    observation_reference_limit: "观测引用达到返回上限",
    evidence_reference_limit: "证据引用达到返回上限",
    OPEN: "未关闭",
    CLOSED: "已关闭",
    OPENED: "已开启",
    REOPENED: "已重新开启",
    UNREPORTED_ASSET: "未申报资产",
    UNOBSERVED_ASSET: "未观测资产",
    DETERMINISTIC: "确定性生成",
    DETERMINISTIC_TEMPLATE: "确定性模板",
    GENERATING: "生成中",
    REVIEWABLE: "可审阅",
    CURRENT_RUN_TRANSITION: "当前运行状态变更",
    OPEN_BACKLOG: "未关闭发现项积压",
    SOURCE_SNAPSHOT: "来源快照",
    OBSERVATION: "观测记录",
    FINDING_OCCURRENCE: "发现项出现记录",
    FINDING_TRANSITION: "发现项状态变更",
    RUNNING: "运行中",
    FAILED_DATA: "数据失败",
    FAILED_PROCESSING: "处理失败",
    COMPLETED: "已完成",
    COMPLETED_WITH_WARNINGS: "已完成但有警告",
    SUCCEEDED: "成功",
    FAILED: "失败",
    LOAD_CUSTOMER: "加载客户输入",
    PULL_CLOUDATLAS: "拉取 CloudAtlas",
    LOAD_NETFLOW: "加载 NetFlow",
    NORMALIZE: "标准化",
    RESOLVE: "解析资产",
    CHECK_FINDINGS: "检查发现项",
    BUILD_REPORT: "构建报告",
    VALIDATE_REPORT: "验证报告",
    PUBLISH: "发布",
    missing_responsibility_value: "缺少责任字段值",
    extra_columns_ignored: "已忽略额外列",
    netflow_invalid_ip: "无效 IP",
    netflow_invalid_protocol: "无效协议",
    netflow_invalid_port: "无效端口",
    netflow_unknown_protocol: "未知协议",
    netflow_invalid_time: "无效时间",
    netflow_invalid_time_range: "无效时间范围",
    netflow_invalid_count: "无效计数",
    netflow_invalid_tcp_flags: "无效 TCP 标志",
    netflow_duplicate_records: "重复记录",
    netflow_ignored_input_columns: "已忽略输入列",
    step_start_failed: "步骤启动失败",
    customer_snapshot_failed: "客户快照失败",
    customer_snapshot_processing_failed: "客户快照处理失败",
    cloudatlas_snapshot_failed: "CloudAtlas 快照失败",
    cloudatlas_snapshot_processing_failed: "CloudAtlas 快照处理失败",
    netflow_snapshot_failed: "NetFlow 快照失败",
    netflow_snapshot_processing_failed: "NetFlow 快照处理失败",
    normalize_contract_failed: "标准化合同校验失败",
    normalize_snapshot_failed: "标准化快照失败",
    normalize_snapshot_unavailable: "标准化快照不可用",
    normalize_persistence_failed: "标准化持久化失败",
    normalize_unexpected_failure: "标准化发生意外错误",
    resolve_contract_failed: "资产解析合同校验失败",
    resolve_persistence_failed: "资产解析持久化失败",
    resolve_unexpected_failure: "资产解析发生意外错误",
    check_findings_contract_failed: "发现项检查合同校验失败",
    check_findings_persistence_failed: "发现项检查持久化失败",
    check_findings_unexpected_failure: "发现项检查发生意外错误",
    build_report_processing_failed: "报告构建处理失败",
    build_report_storage_failed: "报告构建存储失败",
    build_report_contract_failed: "报告构建合同校验失败",
    build_report_input_failed: "报告构建输入失败",
    build_report_persistence_failed: "报告构建持久化失败",
    validate_report_processing_failed: "报告验证处理失败",
    validate_report_storage_failed: "报告验证存储失败",
    validate_report_contract_failed: "报告验证合同校验失败",
    validate_report_persistence_failed: "报告验证持久化失败",
    publish_storage_failed: "发布存储失败",
    publish_contract_failed: "发布合同校验失败",
    publish_failed: "发布失败",
    session_terminated: "会话已终止",
    session_not_recoverable: "会话无法恢复",
    draft_idempotency_key_required: "请提供稳定的幂等键",
    draft_idempotency_conflict: "该幂等键已绑定到另一份治理报告",
    draft_generation_active: "此报告已有正在生成的草稿",
    draft_generation_after_failure_not_supported:
      "当前版本不支持失败后发起新的草稿尝试",
    draft_project_archived: "项目已归档，仅可读取",
    report_not_found: "治理报告不存在",
    report_not_published: "治理报告尚未发布",
    draft_report_contract_unsupported: "此报告合同不支持 AI 治理草稿",
    finding_not_selected: "所有选中的发现项必须在此报告中符合条件",
    evidence_not_bound: "选中的发现项缺少匹配的已持久化证据",
    invalid_bindings: "请选择一至八个不同且符合条件的发现项",
    report_evidence_plan_invalid: "已发布报告的证据计划无效",
    model_not_qualified: "当前模型未通过草稿生成资格校验",
    model_binding_changed: "草稿固定的模型绑定与当前部署配置不一致",
    agent_compose_unavailable: "会话控制面不可用",
    agent_compose_start_failed: "无法启动会话",
    agent_compose_session_pending: "草稿运行已接受，会话标识尚未可见",
    agent_compose_run_status_unknown:
      "草稿运行状态暂无法识别，请复用相同幂等键重试",
    agent_compose_response_contract_failed: "会话控制面返回了无效响应",
    agent_compose_run_failed: "草稿运行已失败",
    agent_compose_session_not_recoverable: "原治理运行会话无法恢复",
    run_idempotency_key_required: "请提供稳定的幂等键",
    run_customer_upload_not_ready: "触发运行前，请选择已校验的客户上传",
    run_netflow_dataset_not_ready: "选中的 NetFlow 数据集不可用",
    run_cloudatlas_source_not_ready: "触发运行前，请启用并校验云图数据源",
    run_cloudatlas_credential_not_ready: "触发运行前，请配置云图运行凭据",
    run_project_archived: "项目已归档，仅可读取",
    run_publication_incomplete: "最新治理运行的成功发布状态不完整",
    run_already_active: "此项目已有正在执行的治理运行",
    run_retry_newer_run_exists: "已有更新的治理运行，此运行已成为历史记录",
    run_retry_completed: "已完成的治理运行不能重试",
    run_retry_customer_input_changed: "固定的客户上传输入已变化",
    run_retry_cloudatlas_input_changed: "固定的云图输入已变化",
    run_retry_cloudatlas_input_unavailable: "无法验证固定的云图输入",
    run_retry_no_failed_step: "此治理运行没有可重试的失败步骤",
    run_processing_not_retryable: "此确定性处理失败需要显式重新运行",
    run_session_still_running: "原会话仍在运行",
    run_session_state_unknown: "原会话的终止状态未知",
    run_session_not_recoverable: "原会话无法恢复",
    run_rerun_required: "请使用新的触发 ID 重新运行此失败运行",
    run_launch_in_progress: "治理 Runner 启动正在进行中",
    run_launch_terminal_use_new_trigger:
      "上次启动在创建运行前已结束，请使用新的触发 ID",
    run_retry_netflow_input_changed: "固定的 NetFlow 数据集输入已变化",
    run_netflow_input_unavailable: "无法验证固定的 NetFlow 数据集输入",
    run_rerun_newer_run_exists: "只能重新运行最新的治理运行",
    run_rerun_trigger_conflict: "此触发 ID 已属于另一治理运行",
    run_retry_in_progress: "重试恢复正在进行中",
  },
  null,
)
